### ISSUE TITLE
Use git submodule instead of using ssh to clone metanorma.com

### ISSUE THREAD

**Issue by kwkwan** [riboseinc/open.ribose.com#11]
It is simpler to use git submodule for project site instead of writing a script to clone, and much easier to make production deployment work too.

**Comment by strogonoff** [comment]
@kwkwan 

I’m not sure I see a problem due to which production deployments don’t “work” with cloning. What submodules could indeed help with is reducing build time and eliminating some of the build logic. The choice to go with cloning was made to avoid the need to commit changes each time a subproject changes, since build time is less relevant.

It doesn’t belong in this project but it’s something to consider, so I filed a corresponding issue against jekyll-theme-open-project (https://github.com/riboseinc/jekyll-theme-open-project/issues/12). Thank you!

**Comment by strogonoff** [comment]
(To clarify, this is definitely on the table, I’m just moving further discussion on this under the abovementioned ticket)
